name: Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node: ['12']

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci --production

      - name: Remove dev packages
        run: npm prune --production --no-audit

      # https://github.com/docker/build-push-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
             ${{ secrets.DOCKER_REPOSITORY }}::${GITHUB_REF#refs/*/}
             ${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
