name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node: ['12']

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  build:
    needs: lint
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
       node: ['12']

    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node }}
         
      - name: Set up .env
        run: echo seting up..
        env: 
          RELEASE_VERSION: :${GITHUB_REF#refs/*/}

      - name: Install dependencies
        run: npm ci --no-audit
        
      - name: Build it
        run: npm run build

      - name: Echo .env
        run: echo ${{ RELEASE_VERSION }}
